/* ////////////////////////////////////////////////////////////////
* 
*   DICTIONARYFORMIDS-CREATOR
*   
*   This file is part of DictionaryForMIDs-Creator
*   Copyright (C) 2012 Karim Mahamane Karimou
*   DictionaryForMIDs-Creator is a GUI wrapper around various
*   DictionaryForMIDs tools, among others we have
*   DictdToDictionaryForMIDs, DictionaryGeneration,
*   JarCreator and BitmapFontGenerator.
*   
*   DictionaryForMIDs-Creator is free software;
*   you can redistribute it and/or modify it under the terms
*   of the GNU General Public License as published by the
*   Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.
*   
*   DictionaryForMIDs-Creator is distributed in the hope that
*   it will be useful, but WITHOUT ANY WARRANTY; without even
*   the implied warranty of MERCHANTABILITY or
*   FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*   	
*   You should have received a copy of the GNU General Public
*   License along with DictionaryForMIDs-Creator;
*   if not, write to the Free Software Foundation, Inc.,
*   51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA
*   
* //////////////////////////////////////////////////////////////// */


package de.kugihan.DfMCreator;

import edu.hws.eck.mdb.I18n;

public class BFGSummary extends javax.swing.JFrame {

    /**
     * Creates new form BFGSummary
     */
    public BFGSummary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textarea.setColumns(20);
        textarea.setRows(5);
        jScrollPane1.setViewportView(textarea);
        fillBFGSummaryTextArea();

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButton1.setText(I18n.tr("generate.bdgSummary")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Hiding the summary window
        this.dispose();
        DfMCreatorMain.dfmCreator.fontTK.proceed();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
               // new BFGSummary().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables

    
    public static BFGSummary getBFGwindow() {
        return new BFGSummary();
    }

    /**
     * fillBFGSummaryTextArea() gets all the needed information
     * and formats them correctly so as to have a clear and neat
     * summary of the Bitmap Font Generation preferences entered
     * by the user.
     */
    private void fillBFGSummaryTextArea() {
        
        textarea.append(I18n.tr("headline.BFGSummary") + "\n\n");
        
        textarea.append(I18n.tr("chosenFont.BFGSummary") + "\n\n");
        textarea.append(DfMCreatorMain.dfmCreator.fontTK.getFontFieldText());
        textarea.append("\n\n");
        
        textarea.append(I18n.tr("fontSize.BFGSummary") + " " );
        textarea.append(DfMCreatorMain.dfmCreator.fontTK.getFontSize());
        textarea.append("\n\n");
        
        textarea.append(I18n.tr("clipTop.BFGSummary") + " ");
        textarea.append(DfMCreatorMain.dfmCreator.fontTK.getClipTob());
        textarea.append("\n\n");
        
        textarea.append(I18n.tr("clipBottom.BFGSummary") + " ");
        textarea.append(DfMCreatorMain.dfmCreator.fontTK.getClipBottom());
        textarea.append("\n\n");
        
        textarea.append(I18n.tr("end.BFGSummary"));
        textarea.append("\n");
    }

}
